# Generated by Django 5.0.1 on 2024-01-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=100)),
                ('tracking_id', models.CharField(max_length=10)),
                ('priority', models.IntegerField()),
                ('current_location', models.CharField()),
                ('destination', models.CharField(max_length=100)),
                ('delivery_date', models.IntegerField(max_length=40)),
            ],
        ),
    ]
